// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	AdAddressid uuid.UUID
	AdStreet    string
	AdCity      string
	AdState     string
	AdZip       string
	AdCountry   string
}

type Order struct {
	OrOrderid         uuid.UUID
	OrUserid          uuid.UUID
	OrTotalamount     float64
	OrOrderstatus     string
	OrPaymentmethod   string
	OrShippingaddress uuid.UUID
	OrCreatedat       pgtype.Timestamp
	OrUpdatedat       pgtype.Timestamp
}

type OrdersProduct struct {
	OrpOrderid    uuid.UUID
	OrpProductid  uuid.UUID
	OrpQuantidad  int32
	OrpTotalprice float64
}

type Product struct {
	PrProductid   uuid.UUID
	PrDescription string
	PrStock       int32
	PrPrice       float64
	PrVbactive    bool
}

type User struct {
	UsUserid    uuid.UUID
	UsFirstname string
	UsLastname  pgtype.Text
	UsEmail     pgtype.Text
	UsVbactive  bool
}
